spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: github-dev-config-bus-application-name
---
spring:
  profiles: test   #测试环境
  application: 
    name: github-test-config-bus-application-name
#  请保存为UTF-8格式
 
 
